apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hello-kube-msg
spec:
  encryptedData:
    msg: AgBwH1TjVGtzAIagrJ+1pv6ufOHp0HP8w64/v4lFIwrPKYrSCFVyaABAOyP6XzJg8bmEJXz0pYFq/mXv/u/WKQpgbsvRx3YSVbE4oniZYukL1Fdy0itxdnlQpK0fF34aNlluEY5LJCXlHylfDgH+10HpYvxMY3psZKvel+mbIwftIEzyTJWi4Py2z5h7o4+2HvWk4ML88AzXay+RDSdQP2qrS6OUVeYyXzKJ17fH/YOKj2eKWwEorkaPNCoZftjzBIXCiyqszhGvIY9rEjTslyS8TYlseVPpoYxUJbZXaoTKDA0Ot1he7JFgL7F1rzh3EbBgUWQAxkx927x6d5lEZFesoajJei8lxROcd90ERXAUMgyIIbCFTjKAJRlqOR9x4wk1va8rMKt1GP6BHZUOmvgc4gTmLBjiqynHmg+eJOVWfvyfABPZIs2BNsgU/B3dS0LtViwLoOHZPzruyGWCffYljpCYONVYGo17IrGs19Q8Xyy4lT1niz7QkEOnnwUp7Prs7eoVXYv3gjzjmziACjOnsAgq5g2Fx5fhtiySebaeP6DoAGlwm8wB7sB/RswQ2vTBdPgrNK5J6XxHYkrpf/4ZIXKGbOS68+chKeFNFPsmz9D6KLP65F6v6XIczjh6xnn7vYUo2THs9EvKVQBeWAdpHGzazokAz4oll9O4og5ziPyuqvhxv+BVWP/7FUnCY91O1qep2D5hSK3BBHbfBOKbVM8In5g5iw==
  template:
    metadata:
      creationTimestamp: null
      name: hello-kube-msg
      namespace: team2

