apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-flux2
spec:
  releaseName: hello-flux2
  chart:
    spec:
      chart: stateless-app
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: kubechamp
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    app:
      env:
        - name: "MESSAGE"
          value: "Hello from the internet on Flux2"
    istioVirtualService:
      enabled: true

    istio-virtual-service:
      host: hello.team1.workload-1.kubechamp.gq
      gateway: istio-system/istio-gateway-default-public
      endpoints:
        - uri: "/"
          destinationPort: 80
          uriType: prefix
          destinationHost: hello-flux2

    
