apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-flux2
spec:
  releaseName: hello-flux2
  chart:
    spec:
      chart: stateless-app
      version: "0.1.1"
      sourceRef:
        kind: HelmRepository
        name: kubechamp
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    app:
      env:
        - name: "MESSAGE"
          value: "Hello from the internet on Flux2"

    